simplemooc/core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^contato/$', views.contact, name='contact')
]

simplemooc/courses/urls.py
from django.conf.urls import url
from . import views

app_name = 'courses'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

simplemooc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('simplemooc.core.urls')),
    url(r'^cursos', include('simplemooc.courses.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/core/models.py
from django.db import models

# Create your models here.

simplemooc/courses/models.py
from django.db import models


class CourseManager(models.Manager):

    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) | models.Q(description__icontains=query)
        )


class Course(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    description = models.TextField('Descrição', blank=True)
    start_date = models.DateField('Data de Início', null=True, blank=True)
    image = models.ImageField(
        upload_to='courses/image', verbose_name='Imagem',
        null=True, blank=True
    )
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    objects = CourseManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['name']

simplemooc/core/views.py
from django.shortcuts import render


def home(request):
    context = {
        'home_link_selected': 'active',
    }
    return render(request, 'home.html', context)


def contact(request):
    context = {
        'contact_link_selected': 'active',
    }
    return render(request, 'contact.html', context)

simplemooc/courses/views.py
from django.shortcuts import render
from .models import Course


def index(request):
    courses = Course.objects.all()
    context = {
        'courses_link_selected': 'active',
        'courses': courses,
    }
    return render(request, 'index.html', context)

simplemooc/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/sticky-footer-navbar.css' %}"
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'core:home' %}">Simple MOOC</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="{{ home_link_selected }}"><a href="{% url 'core:home' %}">Início</a></li>
                <li class="{{ courses_link_selected }}"><a href="{% url 'courses:index'%}">Cursos</a></li>
                <li class="{{ contact_link_selected }}"><a href="{% url 'core:contact' %}">Contato</a></li>
            </ul>
        </div>
    </div>
</nav>

<div id="content">
    {% block content %}{% endblock %}
</div>
<div class="footer-static">
    <footer class="footer-inverse">
        <div class="container">
            <p class="text-muted" style="text-align: center">Place sticky footer content here.</p>
        </div>
    </footer>
</div>
</body>

</html>

simplemooc/core/templates/contact.html
{% extends 'base.html' %}
{% block content %}
<div class="container container-base">
    <h1 style="font-weight: bold">Fale conosco</h1>
    <h4 style="line-height: 50px">Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo
        segue os links para contato:</h4>
    <h4 style="font-weight: bold; line-height: 50px">Links</h4>
    <ul>
        <li>E-mail: <a href="#">contato@simplemooc.com</a></li>
        <li>Twitter: <a href="#">@simplemooc</a></li>
    </ul>
    <hr/>
</div>
{% endblock %}

simplemooc/core/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h1>Uma Simples Plataforma de Ensino a Distância</h1>

            <p class="text-justify" style="text-indent: 1.5em">O Simple MOOC visa simplificar o ensino a distância,
                provendo
                ferramentas objetivas e de fácil uso para
                cursos a distância.</p>
            <button type="button" class="btn btn-primary btn-lg">Saiba mais</button>
        </div>
    </div>

    <div class="container container-default">
        <p class="text-justify" style="text-indent: 1.5em"> um fato conhecido de todos que um leitor se distrairá com o
            conteúdo de texto legível de uma página quando
            estiver examinando sua diagramação. A vantagem de usar Lorem Ipsum é que ele tem uma distribuição normal de
            letras, ao contrário de "Conteúdo aqui, conteúdo aqui", fazendo com que ele tenha uma aparência similar a de
            um
            texto legível. Muitos softwares de publicação e editores de páginas na internet agora usam Lorem Ipsum como
            texto-modelo padrão, e uma rápida busca por 'lorem ipsum' mostra vários websites ainda em sua fase de
            construção. Várias versões novas surgiram ao longo dos anos, eventualmente por acidente, e às vezes de
            propósito
            (injetando humor, e coisas do gênero).</p>

        <p class="text-justify" style="text-indent: 1.5em"> um fato conhecido de todos que um leitor se distrairá com o
            conteúdo de texto legível de uma página quando
            estiver examinando sua diagramação. A vantagem de usar Lorem Ipsum é que ele tem uma distribuição normal de
            letras, ao contrário de "Conteúdo aqui, conteúdo aqui", fazendo com que ele tenha uma aparência similar a de
            um
            texto legível. Muitos softwares de publicação e editores de páginas na internet agora usam Lorem Ipsum como
            texto-modelo padrão, e uma rápida busca por 'lorem ipsum' mostra vários websites ainda em sua fase de
            construção. Várias versões novas surgiram ao longo dos anos, eventualmente por acidente, e às vezes de
            propósito
            (injetando humor, e coisas do gênero).</p>

        <p class="text-justify" style="text-indent: 1.5em"> um fato conhecido de todos que um leitor se distrairá com o
            conteúdo de texto legível de uma página quando
            estiver examinando sua diagramação. A vantagem de usar Lorem Ipsum é que ele tem uma distribuição normal de
            letras, ao contrário de "Conteúdo aqui, conteúdo aqui", fazendo com que ele tenha uma aparência similar a de
            um
            texto legível. Muitos softwares de publicação e editores de páginas na internet agora usam Lorem Ipsum como
            texto-modelo padrão, e uma rápida busca por 'lorem ipsum' mostra vários websites ainda em sua fase de
            construção. Várias versões novas surgiram ao longo dos anos, eventualmente por acidente, e às vezes de
            propósito
            (injetando humor, e coisas do gênero).</p>
    </div>
{% endblock %}

simplemooc/courses/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container container-base">
        <h2 style="font-weight: bold; color: gray">LISTAGEM DE CURSOS</h2>
        <hr width="350px" align="left" role="separator"/>
        <div class="container">
            <h4 style="font-weight: bold">Abaixo a lista de cursos disponíveis na plataforma.</h4>
        </div>

        <hr role="separator"/>

        {% if courses %}
            {% for course in courses %}
                <div class="container" style="margin-top: 40px; padding: 15px">

                    <div class="col-md-4">
                        <a href="#" class="thumbnail" style="max-width: 450px;
                            margin-left: auto; margin-right: auto">
                            {% if course.image %}
                                <img class="img-responsive" src="{{ course.image.url }}"
                                     alt="{{ course.name }}"
                                     style="width:450px;height:250px">
                            {% else %}
                                <img class="img-responsive" src="{% static 'img/no_image.png' %}"
                                     alt="{{ course.name }}"
                                     style="width:450px;height:250px">
                            {% endif %}
                        </a>
                    </div>
                    <div class="col-md-8">
                        <a href="#"><p style="font-size: 16pt">{{ course|upper }}</p></a>
                        <hr role="separator" style="margin-top: -10px"/>
                        {{ course.description|linebreaks }}
                    </div>
                </div>
                <hr role="separator"/>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}